version: '2'

volumes:
  prometheus_data:
    driver: local

networks:
  my-net:
    driver: bridge

services:
  prom:
    image: secureimages/prometheus:2.36.2-alpine-3.16.0
    command:
      - /usr/local/bin/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/var/lib/prometheus/
      - --storage.tsdb.retention.time=2h
    ports:
      - 9090:9090
    networks:
      - my-net
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - 'prometheus_data:/var/lib/prometheus'
