version: '2'

networks:
  my-network:
    driver: bridge

volumes:
  ldap_data:
    driver: local
  ldap_manager:
    driver: local

services:
  ldap:
    image: bitnami/openldap:latest
    ports:
      - '1389:1389'
    environment:
      - BITNAMI_DEBUG=false
      - LDAP_PORT_NUMBER=1389
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=123
      - LDAP_ROOT=dc=zuzu,dc=com
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_CUSTOM_LDIF_DIR=/import
    volumes:
      - 'ldap_data:/bitnami/openldap'
      - './ldap-schema:/import'
    networks:
      - my-network
  ldapmanager:
    image: ldapaccountmanager/lam:latest
    ports:
      - '8080:80'
    environment:
      - LAM_SKIP_PRECONFIGURE=false
      - LDAP_DOMAIN=zuzu.com
      - LDAP_BASE_DN=dc=zuzu,dc=com
      - LDAP_USERS_DN=ou=users,dc=zuzu,dc=com
      - LDAP_GROUPS_DN=ou=groups,dc=zuzu,dc=com
      - LDAP_SERVER=ldap://ldap:1389
      - LDAP_USER=cn=admin,dc=zuzu,dc=com
      - LDAP_ADMIN_PASSWORD=123
      - LDAP_READONLY_USER_PASSWORD=321
    volumes:
      - 'ldap_manager:/var/lib/ldap-account-manager/config'
    networks:
      - my-network
