version: '2'

networks:
  my-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
services:
  redis:
    image: redis:alpine
    # save a snapshot of the DB every 60 seconds if at least 1 write operation was performed
    command: ["--save", "60", "1",  "--loglevel", "warning"]
    networks:
      - my-network
    volumes:
      - 'redis_data:/data'
  python:
    build: python
    depends_on:
      - redis
    networks:
      - my-network
    volumes:
      - './python/sources:/app:ro' #needed only during dev
