bind_port: 8080
ldap:
  host: 192.168.100.24
  port: 1389
  user: "cn=admin,dc=zuzu,dc=com"
  password: "123"
  base_dn: "dc=zuzu,dc=com"
  users_dn: "ou=users,dc=zuzu,dc=com"
  groups_dn: "ou=groups,dc=zuzu,dc=com"
  sync_seconds: 20 
jwt:
  alg: HS256
  secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
  expiration_seconds: 600 # 10 minutes
