version: '2'

networks:
  my-network:
    driver: bridge

volumes:
  ram-disk:
    driver_opts:
      type: tmpfs
      o: "size=64m"
      device: tmpfs

services:
  python:
    build: python
    ports:
      - '8080:8080'
    networks:
      - my-network
    environment:
      - GUNICORN_WORKERS=3
      - GUNICORN_THREADS=10
      - GUNICORN_PORT=8080
      - GUNICORN_WORKER_CLASS=gevent
    networks:
      - my-network
    volumes:
      - 'ram-disk:/my-tmp-dir'
      # mount sources (needed during development - to not rebuild images on every py change)
      - './python/sources:/app:ro'
    networks:
      - my-network
  slow-backend:
    build: slow-backend
    networks:
      - my-network
