version: '2'

networks:
  my-network:
    driver: bridge

services:
  python:
    build: python
    ports:
      - '8080:8080'
    networks:
      - my-network
    environment:
      - GUNICORN_WORKERS=3
      - GUNICORN_THREADS=10
      - GUNICORN_PORT=8080
    networks:
      - my-network
    volumes:
      # mount sources (needed during development - to not rebuild images on every py change)
      - './python/sources:/app:ro'
    networks:
      - my-network
